/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class Pet {
  getFieldTypeMap() {
      let fieldTypeMap = new Map();
      fieldTypeMap.set('PetID', 'String');
      fieldTypeMap.set('PetName', 'String');
      fieldTypeMap.set('PetDesc', 'String');
      fieldTypeMap.set('Ownership', 'String');
      fieldTypeMap.set('UserId', 'String');
      return fieldTypeMap;
  }

  getClassName() {
      return 'Pet';
  }

  getPrimaryKeyList() {
      let primaryKeyList = [];
      primaryKeyList.push('PetID');
      return primaryKeyList;
  }

  getIndexList() {
      let indexList = [];
      indexList.push('PetID');
      return indexList;
  }

  getEncryptedFieldList() {
      let encryptedFieldList = [];
      return encryptedFieldList;
  }

  setPetID(PetID) {
      this.PetID = PetID;
  }

  getPetID() {
      return this.PetID;
  }

  setPetName(PetName) {
      this.PetName = PetName;
  }

  getPetName() {
      return this.PetName;
  }

  setPetDesc(PetDesc) {
      this.PetDesc = PetDesc;
  }

  getPetDesc() {
      return this.PetDesc;
  }

  setOwnership(Ownership) {
      this.Ownership = Ownership;
  }

  getOwnership() {
      return this.Ownership;
  }

  setUserId(UserId) {
      this.UserId = UserId;
  }

  getUserId() {
      return this.UserId;
  }
}

module.exports = {Pet}