/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class PetTrack {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('RecordID', 'String');
        fieldTypeMap.set('PetID', 'String');
        fieldTypeMap.set('Date', 'String');
        fieldTypeMap.set('RecordTime', 'String');
        fieldTypeMap.set('Longtitude', 'String');
        fieldTypeMap.set('Latitude', 'String');
        fieldTypeMap.set('Remark', 'String');
        return fieldTypeMap;
    }

    getClassName() {
        return 'PetTrack';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('RecordID');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        indexList.push('PetID,Date');
        indexList.push('RecordID');
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setRecordID(RecordID) {
        this.RecordID = RecordID;
    }

    getRecordID() {
        return this.RecordID;
    }

    setPetID(PetID) {
        this.PetID = PetID;
    }

    getPetID() {
        return this.PetID;
    }

    setDate(Date) {
        this.Date = Date;
    }

    getDate() {
        return this.Date;
    }

    setRecordTime(RecordTime) {
        this.RecordTime = RecordTime;
    }

    getRecordTime() {
        return this.RecordTime;
    }

    setLongtitude(Longtitude) {
        this.Longtitude = Longtitude;
    }

    getLongtitude() {
        return this.Longtitude;
    }

    setLatitude(Latitude) {
        this.Latitude = Latitude;
    }

    getLatitude() {
        return this.Latitude;
    }

    setRemark(Remark) {
        this.Remark = Remark;
    }

    getRemark() {
        return this.Remark;
    }
}

module.exports = {PetTrack}