/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class User {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('userID', 'String');
        fieldTypeMap.set('remark', 'Text');
        fieldTypeMap.set('userName', 'String');
        fieldTypeMap.set('userType', 'String');
        fieldTypeMap.set('photoUrl', 'Text');
        fieldTypeMap.set('created_at', 'Long');
        fieldTypeMap.set('last_login', 'Long');
        return fieldTypeMap;
    }

    getClassName() {
        return 'User';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('userID');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        indexList.push('userID');
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setUserID(userID) {
        this.userID = userID;
    }

    getUserID() {
        return this.userID;
    }

    setRemark(remark) {
        this.remark = remark;
    }

    getRemark() {
        return this.remark;
    }

    setUserName(userName) {
        this.userName = userName;
    }

    getUserName() {
        return this.userName;
    }

    setUserType(userType) {
        this.userType = userType;
    }

    getUserType() {
        return this.userType;
    }

    setPhotoUrl(photoUrl) {
        this.photoUrl = photoUrl;
    }

    getPhotoUrl() {
        return this.photoUrl;
    }

    setCreated_at(created_at) {
        this.created_at = created_at;
    }

    getCreated_at() {
        return this.created_at;
    }

    setLast_login(last_login) {
        this.last_login = last_login;
    }

    getLast_login() {
        return this.last_login;
    }
}

module.exports = {User}