/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.pettrackingdemo.db;



/**
 * Definition of ObjectType Pet.
 *
 * @since 2022-04-20
 */
//@PrimaryKeys({"PetID"})
//@Indexes({"idx_id:PetID"})
public final class Pet {
    private String PetID;

    private String PetName;

    private String PetDesc;

    private String Ownership;

    public void setPetID(String PetID) {
        this.PetID = PetID;
    }

    public String getPetID() {
        return PetID;
    }

    public void setPetName(String PetName) {
        this.PetName = PetName;
    }

    public String getPetName() {
        return PetName;
    }

    public void setPetDesc(String PetDesc) {
        this.PetDesc = PetDesc;
    }

    public String getPetDesc() {
        return PetDesc;
    }

    public void setOwnership(String Ownership) {
        this.Ownership = Ownership;
    }

    public String getOwnership() {
        return Ownership;
    }

}
