/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.pettrackingdemo.db;



/**
 * Definition of ObjectType PetTrack.
 *
 * @since 2022-04-20
 */

public final class PetTrack {
    private String RecordID;

    private String PetID;

    private String Date;

    private String RecordTime;

    private String Longtitude;

    private String Latitude;

    private String Remark;



    public void setRecordID(String RecordID) {
        this.RecordID = RecordID;
    }

    public String getRecordID() {
        return RecordID;
    }

    public void setPetID(String PetID) {
        this.PetID = PetID;
    }

    public String getPetID() {
        return PetID;
    }

    public void setDate(String Date) {
        this.Date = Date;
    }

    public String getDate() {
        return Date;
    }

    public void setRecordTime(String RecordTime) {
        this.RecordTime = RecordTime;
    }

    public String getRecordTime() {
        return RecordTime;
    }

    public void setLongtitude(String Longtitude) {
        this.Longtitude = Longtitude;
    }

    public String getLongtitude() {
        return Longtitude;
    }

    public void setLatitude(String Latitude) {
        this.Latitude = Latitude;
    }

    public String getLatitude() {
        return Latitude;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getRemark() {
        return Remark;
    }

}
